apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: social-network
build:
  artifacts:
    - image: martcl/another-social-network
      context: another-social-network
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
          - BP_GO_TARGETS=./cmd/server/main.go

manifests:
  rawYaml:
    - k8s/another-social-network.yaml
    - k8s/ingress.yml
    - k8s/couchdb.yaml
