apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
  - host: social-network.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: another-social-network-service
            port:
              number: 3000

  - host: couchdb.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: couchdb-service
            port:
              number: 5984

