apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
  - host: social-network.local
    http:
      paths:
      - pathType: Prefix
        path: "/.well-known/webfinger"
        backend:
          service:
            name: webfinger-service
            port:
              number: 3000
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: social-network
            port:
              number: 3000
  - host: couchdb.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: couchdb-service
            port:
              number: 5984

